version: '3.8'

services:
  backend:
    build:
      context: backend
    ports:
      - "8000:8000"
    depends_on:
      - exam_db
    networks:
      - web
      - persistence


  exam_db:
    image: postgres:12.16
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - exam_data:/var/lib/postgresql/data
    env_file:
      - backend/.env
    networks:
      - persistence


  frontend:
    build:
      context: frontend
    ports:
      - "4200:4200"
    networks:
      - web


volumes:
  exam_data:

networks:
  web:
  persistence:
