version: '3.8'
services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    volumes:
      - .:/backend
    depends_on:
      - database
  database:
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=exam_net
    volumes:
      - ./database:/var/lib/postgresql/data
  frontend:
    build:
      context: ./frontend
    ports:
      - "4200:4200"
    volumes:
      - .:/frontend
    depends_on:
      - backend

volumes:
  postgres_data:
    driver: local