version: '3.8'
services:
  backend:
    build:
      context: backend
    ports:
      - "8000:8000"
    depends_on:
      - exam_db
    volumes:
      - ./backend:/app
  exam_db:
    image: postgres:12.16
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./database:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=exam_net
  frontend:
    build:
      context: frontend
    volumes:
      - ./frontend:/app
    ports:
      - "4200:4200"
