# Generated by Django 4.2.7 on 2023-11-23 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='exam_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='ActiveExam',
            fields=[
                ('active_exam_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('activated_at', models.DateTimeField(auto_now_add=True)),
                ('duration', models.DateTimeField()),
                ('token', models.CharField(max_length=15)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.exam')),
            ],
        ),
    ]
