# Generated by Django 4.2.7 on 2023-12-01 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activeexam',
            name='activated_at',
        ),
        migrations.AlterField(
            model_name='activeexam',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='activeexam',
            name='token',
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
