# Generated by Django 4.2.7 on 2023-11-25 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('exam', '0002_alter_activeexam_exam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activeexam',
            name='exam',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='exam.exam'),
        ),
    ]
