# Generated by Django 4.2.7 on 2023-11-13 16:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='topic',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
