# Generated by Django 4.2.7 on 2023-11-13 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_question_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='latest_version',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='question',
            name='latest_version',
            field=models.BooleanField(default=True),
        ),
    ]
