# Generated by Django 4.2.7 on 2023-11-28 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('questions', '0003_answer_latest_version_question_latest_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers',
                                    to='questions.question'),
        ),
    ]
